In [73]:
import numpy as np
import pandas as pd

In [74]:
df = pd.DataFrame([[8,8,1], [7,9,1], [6,10,0], [5,12,0]], columns=["cgpa", "profile_score", "placed"])

In [75]:
df

cgpa  profile_score  placed
0     8              8       1
1     7              9       1
2     6             10       0
3     5             12       0

In [76]:
def initialize_parameters(layer_dim):
    np.random.seed(42)
    parameters = {}
    L = len(layer_dim)

    for i in range(1, L):
        parameters["W" + str(i)] = np.ones((layer_dim[i-1], layer_dim[i]))*0.1
        parameters["b" + str(i)] = np.zeros((layer_dim[i], 1))

    return parameters

In [77]:
# sigmoid function
def sigmoid(z):
    A = 1 / (1+ np.exp(-z))
    return A

In [78]:
def linear_forward(A_pre, W, b):

    z = np.dot(W.T, A_pre) + b

    A = sigmoid(z) 

    return A

In [79]:
def L_layer_forward(X, parameters): 
    A = X
    L = len(parameters) // 2 ## number of layers in the neural network

    for i in range(1, L+1):
        A_pre = A   # A_pre is the input
        W1 = parameters["W" + str(i)]
        b1 = parameters["b" + str(i)]

        print("A" + str(i-1) + ": ", A_pre)
        print("W" + str(i) + ": ", W1)
        print("b" + str(i) + ": ", b1)
        print("--"*20)

        A = linear_forward(A_pre, W1, b1)
        print("A" + str(i) + ": ", A )
        print("**"*20)
    return A, A_pre

In [80]:
def update_parameters(y, y_hat, parameters, X, A1):
    parameters["W2"][0][0] = parameters["W2"][0][0] - 0.001*(-1 * (y-y_hat) * A1[0][0])
    parameters["W2"][1][0] = parameters["W2"][1][0] - 0.001*(-1 * (y-y_hat) * A1[1][0])
    parameters["b2"][0][0] = parameters["b2"][0][0] - 0.001*(-1 * (y-y_hat))
    
    parameters["W1"][0][0] = parameters["W1"][0][0] - 0.001*(-1 * (y-y_hat) * parameters["W2"][0][0] * A1[0][0] * (1-A1[0][0]) * X[0][0])
    parameters["W1"][0][1] = parameters["W1"][0][1] - 0.001*(-1 * (y-y_hat) * parameters["W2"][0][0] * A1[0][0] * (1-A1[0][0]) * X[1][0])
    parameters["b1"][0][0] = parameters["b1"][0][0] - 0.001*(-1 * (y-y_hat) * parameters["W2"][0][0] * A1[0][0] * (1-A1[0][0]))
    
    parameters["W1"][1][0] = parameters["W1"][1][0] - 0.001*(-1 * (y-y_hat) * parameters["W2"][1][0] * A1[1][0] * (1-A1[1][0]) * X[0][0])
    parameters["W1"][1][1] = parameters["W1"][1][1] - 0.001*(-1 * (y-y_hat) * parameters["W2"][1][0] * A1[1][0] * (1-A1[1][0]) * X[1][0])
    parameters["b1"][1][0] = parameters["b1"][1][0] - 0.001*(-1 * (y-y_hat) * parameters["W2"][1][0] * A1[1][0] * (1-A1[1][0]))
    
update_parameters(y, y_hat, parameters, X, A1)

In [81]:
X = df.iloc[:,0:2].values[0].reshape(2,1)
X

array([[8],
       [8]], dtype=int64)

In [82]:
X = df.iloc[:,0:2].values[0].reshape(2,1)
y = df.iloc[:,-1].values[0]

# parameters initialization
parameters = initialize_parameters([2,2,1])

y_hat , A1 = L_layer_forward(X, parameters)
y_hat = y_hat[0][0]

update_parameters(y, y_hat, parameters, X, A1)
Loss = (-y*np.log(y_hat) - (1-y) * np.log(1-y_hat))
print("Loss of first student: ", Loss)

A0:  [[8]
 [8]]
W1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
----------------------------------------
A1:  [[0.83201839]
 [0.83201839]]
****************************************
A1:  [[0.83201839]
 [0.83201839]]
W2:  [[0.1]
 [0.1]]
b2:  [[0.]]
----------------------------------------
A2:  [[0.54150519]]
****************************************
Loss of first student:  0.613402628898913


In [83]:
X = df.iloc[:,0:2].values[1].reshape(2,1)
y = df.iloc[:,-1].values[1]
X, y

(array([[7],
        [9]], dtype=int64),
 1)

In [84]:
X = df.iloc[:,0:2].values[1].reshape(2,1)
y = df.iloc[:,-1].values[1]

# parameters initialization
parameters = initialize_parameters([2,2,1])

y_hat , A1 = L_layer_forward(X, parameters)
y_hat = y_hat[0][0]

update_parameters(y, y_hat, parameters, X, A1)
Loss = (-y*np.log(y_hat) - (1-y) * np.log(1-y_hat))
print("Loss of first student: ", Loss)

A0:  [[7]
 [9]]
W1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
----------------------------------------
A1:  [[0.83201839]
 [0.83201839]]
****************************************
A1:  [[0.83201839]
 [0.83201839]]
W2:  [[0.1]
 [0.1]]
b2:  [[0.]]
----------------------------------------
A2:  [[0.54150519]]
****************************************
Loss of first student:  0.613402628898913


In [85]:
X = df.iloc[:,0:2].values[2].reshape(2,1)
y = df.iloc[:,-1].values[2]

# parameters initialization
parameters = initialize_parameters([2,2,1])

y_hat , A1 = L_layer_forward(X, parameters)
y_hat = y_hat[0][0]

update_parameters(y, y_hat, parameters, X, A1)
Loss = (-y*np.log(y_hat) - (1-y) * np.log(1-y_hat))
print("Loss of first student: ", Loss)

A0:  [[ 6]
 [10]]
W1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
----------------------------------------
A1:  [[0.83201839]
 [0.83201839]]
****************************************
A1:  [[0.83201839]
 [0.83201839]]
W2:  [[0.1]
 [0.1]]
b2:  [[0.]]
----------------------------------------
A2:  [[0.54150519]]
****************************************
Loss of first student:  0.7798063059256977


In [86]:
X = df.iloc[:,0:2].values[3].reshape(2,1)
y = df.iloc[:,-1].values[3]

# parameters initialization
parameters = initialize_parameters([2,2,1])

y_hat , A1 = L_layer_forward(X, parameters)
y_hat = y_hat[0][0]

update_parameters(y, y_hat, parameters, X, A1)
Loss = (-y*np.log(y_hat) - (1-y) * np.log(1-y_hat))
print("Loss of first student: ", Loss)

A0:  [[ 5]
 [12]]
W1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
----------------------------------------
A1:  [[0.84553473]
 [0.84553473]]
****************************************
A1:  [[0.84553473]
 [0.84553473]]
W2:  [[0.1]
 [0.1]]
b2:  [[0.]]
----------------------------------------
A2:  [[0.54217627]]
****************************************
Loss of first student:  0.781271047731989


In [87]:
parameters

{'W1': array([[0.09996476, 0.09991542],
        [0.09996476, 0.09991542]]),
 'b1': array([[-7.04867177e-06],
        [-7.04867177e-06]]),
 'W2': array([[0.09954157],
        [0.09954157]]),
 'b2': array([[-0.00054218]])}

In [88]:
# parameters initialization
parameters = initialize_parameters([2,2,1])
epochs = 50

for i in range(epochs):

    Loss = []

    for j in range(df.shape[0]):
        
        X = df.iloc[:,0:2].values[j].reshape(2,1)
        y = df.iloc[:,-1].values[j]

        y_hat , A1 = L_layer_forward(X, parameters)
        y_hat = y_hat[0][0]
        update_parameters(y, y_hat, parameters, X, A1)
        
        Loss.append(-y*np.log(y_hat) - (1-y) * np.log(1-y_hat))
    
    print("Epoch - ", i+1, "<-->", "Loss - ", np.array(Loss).mean())

parameters

A0:  [[8]
 [8]]
W1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
----------------------------------------
A1:  [[0.83201839]
 [0.83201839]]
****************************************
A1:  [[0.83201839]
 [0.83201839]]
W2:  [[0.1]
 [0.1]]
b2:  [[0.]]
----------------------------------------
A2:  [[0.54150519]]
****************************************
A0:  [[7]
 [9]]
W1:  [[0.10005146 0.10005146]
 [0.10005146 0.10005146]]
b1:  [[6.43254269e-06]
 [6.43254269e-06]]
----------------------------------------
A1:  [[0.83213433]
 [0.83213433]]
****************************************
A1:  [[0.83213433]
 [0.83213433]]
W2:  [[0.10038148]
 [0.10038148]]
b2:  [[0.00045849]]
----------------------------------------
A2:  [[0.54178239]]
****************************************
A0:  [[ 6]
 [10]]
W1:  [[0.10009661 0.10010951]
 [0.10009661 0.10010951]]
b1:  [[1.28820601e-05]
 [1.28820601e-05]]
----------------------------------------
A1:  [[0.83223611]
 [0.83226492]]
****************************************
A1

{'W1': array([[0.1007985 , 0.09760157],
        [0.10080901, 0.09755309]]),
 'b1': array([[-7.88614844e-05],
        [-8.08324641e-05]]),
 'W2': array([[0.09305353],
        [0.0930812 ]]),
 'b2': array([[-0.00789507]])}

## Same above thing with Pytorch

In [89]:
import torch
from torch import nn
torch.__version__

'2.4.1+cpu'

In [90]:
df

cgpa  profile_score  placed
0     8              8       1
1     7              9       1
2     6             10       0
3     5             12       0

In [91]:
X = df.iloc[:,0:2].values
y = df.iloc[:,-1].values

In [92]:
# turn data into tensors
X = torch.from_numpy(X).type(torch.float)
y = torch.from_numpy(y).type(torch.float)

In [93]:
X, y

(tensor([[ 8.,  8.],
         [ 7.,  9.],
         [ 6., 10.],
         [ 5., 12.]]),
 tensor([1., 1., 0., 0.]))

In [94]:
# setting up the device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [95]:
# Now lets construct a model class

class student(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear_layer_stack = nn.Sequential(
        nn.Linear(in_features=2, out_features=2),
        nn.Linear(in_features=2, out_features=1))

  def forward(self, x):
    return self.linear_layer_stack(x)

model = student().to(device)

In [96]:
model

student(
  (linear_layer_stack): Sequential(
    (0): Linear(in_features=2, out_features=2, bias=True)
    (1): Linear(in_features=2, out_features=1, bias=True)
  )
)

In [97]:
model.state_dict()

OrderedDict([('linear_layer_stack.0.weight',
              tensor([[-0.1559,  0.4590],
                      [-0.0456, -0.3955]])),
             ('linear_layer_stack.0.bias', tensor([-0.0492,  0.1022])),
             ('linear_layer_stack.1.weight', tensor([[0.6637, 0.2673]])),
             ('linear_layer_stack.1.bias', tensor([-0.0307]))])

In [98]:
# total_trainable_parameters = [2x2,+ 2 bias], [2x1,+ 1 bias] => 4+2+2+1 => 9
total_params = sum(
	param.numel() for param in model.parameters()
)
total_params

9

In [99]:
# Given weights and biases
weights = [
    torch.tensor([[0.1, 0.1], [0.1, 0.1]], dtype=torch.float32),  # fc1 weight
    torch.tensor([0., 0.], dtype=torch.float32),                 # fc1 bias
    torch.tensor([[0.1], [0.1]], dtype=torch.float32),           # fc2 weight
    torch.tensor([0.], dtype=torch.float32)                      # fc2 bias
]

In [100]:
weights

[tensor([[0.1000, 0.1000],
         [0.1000, 0.1000]]),
 tensor([0., 0.]),
 tensor([[0.1000],
         [0.1000]]),
 tensor([0.])]

In [101]:
# Assign the weights to the Sequential layers
with torch.no_grad():
    model.linear_layer_stack[0].weight.copy_(weights[0])  # First Linear Layer (fc1) weights
    model.linear_layer_stack[0].bias.copy_(weights[1])    # First Linear Layer (fc1) bias
    model.linear_layer_stack[1].weight.copy_(weights[2].T)  # Second Linear Layer (fc2) weights
    model.linear_layer_stack[1].bias.copy_(weights[3])    # Second Linear Layer (fc2) bias

# Verify the assigned weights
print("Layer 1 weights:", model.linear_layer_stack[0].weight)
print("Layer 1 bias:", model.linear_layer_stack[0].bias)
print("Layer 2 weights:", model.linear_layer_stack[1].weight)
print("Layer 2 bias:", model.linear_layer_stack[1].bias)

Layer 1 weights: Parameter containing:
tensor([[0.1000, 0.1000],
        [0.1000, 0.1000]], requires_grad=True)
Layer 1 bias: Parameter containing:
tensor([0., 0.], requires_grad=True)
Layer 2 weights: Parameter containing:
tensor([[0.1000, 0.1000]], requires_grad=True)
Layer 2 bias: Parameter containing:
tensor([0.], requires_grad=True)


In [102]:
model.state_dict()

OrderedDict([('linear_layer_stack.0.weight',
              tensor([[0.1000, 0.1000],
                      [0.1000, 0.1000]])),
             ('linear_layer_stack.0.bias', tensor([0., 0.])),
             ('linear_layer_stack.1.weight', tensor([[0.1000, 0.1000]])),
             ('linear_layer_stack.1.bias', tensor([0.]))])

In [103]:
model.parameters

<bound method Module.parameters of student(
  (linear_layer_stack): Sequential(
    (0): Linear(in_features=2, out_features=2, bias=True)
    (1): Linear(in_features=2, out_features=1, bias=True)
  )
)>

In [104]:
# loss_fc and optimizer
loss_fc = nn.BCELoss() 

optimizer = torch.optim.Adam(params = model.parameters(),
                            lr = 0.001)

In [105]:
# building a training and evaluation loop

epochs = 100

for epoch in range(epochs):

  model.train()

  # forward pass
  y_logits = model(X).squeeze()
  y_pred = torch.round(torch.sigmoid(y_logits))

  # calculate the loss/accuarcy
  loss = loss_fc(y_logits, y)

  # optimizer zero grad
  optimizer.zero_grad()

  # backpropagation
  loss.backward()

  # optimizer step (perform gradient descent)
  optimizer.step()

  # testing
  model.eval()
  with torch.inference_mode():

    # forward pass
    test_logits = model(X).squeeze()
    test_pred = torch.round(torch.sigmoid(test_logits))

    # calculate the loss/accuarcy
    test_loss = loss_fc(test_logits, y)


# lets print out what is happening
    if epoch % 10 == 0:
        print(f"Epoch: {epoch} | Loss: {loss:.5f}")

Epoch: 0 | Loss: 0.77001
Epoch: 10 | Loss: 0.72479
Epoch: 20 | Loss: 0.70717
Epoch: 30 | Loss: 0.70041
Epoch: 40 | Loss: 0.69193
Epoch: 50 | Loss: 0.68264
Epoch: 60 | Loss: 0.67306
Epoch: 70 | Loss: 0.66263
Epoch: 80 | Loss: 0.65129
Epoch: 90 | Loss: 0.63895


In [106]:
model.state_dict()

OrderedDict([('linear_layer_stack.0.weight',
              tensor([[0.1773, 0.0443],
                      [0.1773, 0.0443]])),
             ('linear_layer_stack.0.bias', tensor([0.0340, 0.0340])),
             ('linear_layer_stack.1.weight', tensor([[0.1446, 0.1446]])),
             ('linear_layer_stack.1.bias', tensor([0.0319]))])

In [107]:
parameters

{'W1': array([[0.1007985 , 0.09760157],
        [0.10080901, 0.09755309]]),
 'b1': array([[-7.88614844e-05],
        [-8.08324641e-05]]),
 'W2': array([[0.09305353],
        [0.0930812 ]]),
 'b2': array([[-0.00789507]])}