In [195]:
import numpy as np
import pandas as pd

In [196]:
df = pd.DataFrame([[8,8,4], [7,9,5], [6,10,6], [5,12,7]], columns=["cgpa", "profile_score", "lpa"])

In [197]:
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [198]:
def initialize_parameters(layer_dim):
    np.random.seed(42)
    parameters = {}
    L = len(layer_dim)

    for i in range(1, L):
        parameters["W" + str(i)] = np.ones((layer_dim[i-1], layer_dim[i]))*0.1
        parameters["b" + str(i)] = np.zeros((layer_dim[i], 1))

    return parameters

### understanding

In [199]:
layer_dim1 = [2,2,1]
parameters = {}
parameters["W" + str(1)] = np.ones((layer_dim1[1-1], layer_dim1[1]))*0.1
parameters

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]])}

In [200]:
parameters["b" + str(1)] = np.zeros((layer_dim1[1], 1))
parameters

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]])}

In [201]:
parameters["W" + str(2)] = np.ones((layer_dim1[2-1], layer_dim1[2]))*0.1
parameters["b" + str(2)] = np.zeros((layer_dim1[2], 1))
parameters

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [202]:
def linear_forward(A_pre, W, b):

    z = np.dot(W.T, A_pre) + b

    return z

### forward loop

In [203]:
def L_layer_forward(X, parameters): 
    A = X
    L = len(parameters) // 2 ## number of layers in the neural network

    for i in range(1, L+1):
        A_pre = A   # A_pre is the input
        W1 = parameters["W" + str(i)]
        b1 = parameters["b" + str(i)]

        print("A" + str(i-1) + ": ", A_pre)
        print("W" + str(i) + ": ", W1)
        print("b" + str(i) + ": ", b1)
        print("--"*20)

        A = linear_forward(A_pre, W1, b1)
        print("A" + str(i) + ": ", A )
        print("**"*20)
    return A, A_pre

In [204]:
X = df.iloc[:,0:2].values[0].reshape(2,1)
y = df.iloc[:,-1].values[0]

### understanding of code

In [205]:
X

array([[8],
       [8]], dtype=int64)

In [206]:
y

4

In [207]:
len(parameters)//2

2

In [208]:
A_p = X
W9 = parameters["W" + str(2)]
b9 = parameters["b" + str(2)]
W9, b9

(array([[0.1],
        [0.1]]),
 array([[0.]]))

In [209]:
print("A" + str(2-1) + ": ", A_p)
print("W" + str(2) + ": ", W9)
print("b" + str(2) + ": ", b9)
print("--"*20)

A1:  [[8]
 [8]]
W2:  [[0.1]
 [0.1]]
b2:  [[0.]]
----------------------------------------


In [210]:
A = linear_forward(A_p, W9, b9)
print("A" + str(2) + ": ", A )
print("**"*20)

A2:  [[1.6]]
****************************************


## First student

In [211]:
X = df.iloc[:,0:2].values[0].reshape(2,1)
y = df.iloc[:,-1].values[0]

# parameters initialization
parameters = initialize_parameters([2,2,1])

y_hat , A1 = L_layer_forward(X, parameters)

A0:  [[8]
 [8]]
W1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
----------------------------------------
A1:  [[1.6]
 [1.6]]
****************************************
A1:  [[1.6]
 [1.6]]
W2:  [[0.1]
 [0.1]]
b2:  [[0.]]
----------------------------------------
A2:  [[0.32]]
****************************************


In [212]:
# A0 -> is the input
# A1, A2 are the out of the notes after forward propagation

In [213]:
# calculate the loss (y-y-hat)**2

In [214]:
(y - y_hat)**2

array([[13.5424]])

### updaing the parameters

In [215]:
# rule is
# W_new = W_old - lr*(derivative of loss wrt W_old)

In [216]:
def update_parameters(y, y_hat, parameters, X, A1):
    parameters["W2"][0][0] = parameters["W2"][0][0] - 0.001*(-2 * (y-y_hat) * A1[0][0])
    parameters["W2"][1][0] = parameters["W2"][1][0] - 0.001*(-2 * (y-y_hat) * A1[1][0])
    parameters["b2"][0][0] = parameters["b2"][0][0] - 0.001*(-2 * (y-y_hat))
    
    parameters["W1"][0][0] = parameters["W1"][0][0] - 0.001*(-2 * (y-y_hat) * parameters["W2"][0][0] * X[0][0])
    parameters["W1"][0][1] = parameters["W1"][0][1] - 0.001*(-2 * (y-y_hat) * parameters["W2"][0][0] * X[1][0])
    parameters["b1"][0][0] = parameters["b1"][0][0] - 0.001*(-2 * (y-y_hat) * parameters["W2"][0][0])
    
    parameters["W1"][1][0] = parameters["W1"][1][0] - 0.001*(-2 * (y-y_hat) * parameters["W2"][1][0] * X[0][0])
    parameters["W1"][1][1] = parameters["W1"][1][1] - 0.001*(-2 * (y-y_hat) * parameters["W2"][1][0] * X[1][0])
    parameters["b1"][1][0] = parameters["b1"][1][0] - 0.001*(-2 * (y-y_hat) * parameters["W2"][1][0])
    
update_parameters(y, y_hat, parameters, X, A1)

C:\Users\kumar\AppData\Local\Temp\ipykernel_17012\1378376096.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters["W2"][0][0] = parameters["W2"][0][0] - 0.001*(-2 * (y-y_hat) * A1[0][0])
C:\Users\kumar\AppData\Local\Temp\ipykernel_17012\1378376096.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters["W2"][1][0] = parameters["W2"][1][0] - 0.001*(-2 * (y-y_hat) * A1[1][0])
C:\Users\kumar\AppData\Local\Temp\ipykernel_17012\1378376096.py:4: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this 

In [217]:
parameters["W2"][0][0], parameters["W2"][1][0], parameters["b2"][0][0]

(0.111776, 0.111776, 0.007359999999999999)

In [218]:
parameters["W1"][1][0]

0.10658137088

In [219]:
parameters

{'W1': array([[0.10658137, 0.10658137],
        [0.10658137, 0.10658137]]),
 'b1': array([[0.00082267],
        [0.00082267]]),
 'W2': array([[0.111776],
        [0.111776]]),
 'b2': array([[0.00736]])}

## Second student

In [220]:
X = df.iloc[:,0:2].values[1].reshape(2,1)
y = df.iloc[:,-1].values[1]

y_hat , A1 = L_layer_forward(X, parameters)

A0:  [[7]
 [9]]
W1:  [[0.10658137 0.10658137]
 [0.10658137 0.10658137]]
b1:  [[0.00082267]
 [0.00082267]]
----------------------------------------
A1:  [[1.70612461]
 [1.70612461]]
****************************************
A1:  [[1.70612461]
 [1.70612461]]
W2:  [[0.111776]
 [0.111776]]
b2:  [[0.00736]]
----------------------------------------
A2:  [[0.38876757]]
****************************************


In [221]:
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [222]:
X = df.iloc[:,0:2].values[1].reshape(2,1)
X

array([[7],
       [9]], dtype=int64)

In [223]:
y = df.iloc[:,-1].values[1]
y

5

In [224]:
update_parameters(y, y_hat, parameters, X, A1)

C:\Users\kumar\AppData\Local\Temp\ipykernel_17012\1378376096.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters["W2"][0][0] = parameters["W2"][0][0] - 0.001*(-2 * (y-y_hat) * A1[0][0])
C:\Users\kumar\AppData\Local\Temp\ipykernel_17012\1378376096.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters["W2"][1][0] = parameters["W2"][1][0] - 0.001*(-2 * (y-y_hat) * A1[1][0])
C:\Users\kumar\AppData\Local\Temp\ipykernel_17012\1378376096.py:4: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this 

In [225]:
parameters

{'W1': array([[0.11481311, 0.11716504],
        [0.11481311, 0.11716504]]),
 'b1': array([[0.00199863],
        [0.00199863]]),
 'W2': array([[0.12751067],
        [0.12751067]]),
 'b2': array([[0.01658246]])}

## third student

In [226]:
X = df.iloc[:,0:2].values[2].reshape(2,1)
y = df.iloc[:,-1].values[2]

y_hat , A1 = L_layer_forward(X, parameters)

A0:  [[ 6]
 [10]]
W1:  [[0.11481311 0.11716504]
 [0.11481311 0.11716504]]
b1:  [[0.00199863]
 [0.00199863]]
----------------------------------------
A1:  [[1.83900839]
 [1.8766392 ]]
****************************************
A1:  [[1.83900839]
 [1.8766392 ]]
W2:  [[0.12751067]
 [0.12751067]]
b2:  [[0.01658246]]
----------------------------------------
A2:  [[0.49036719]]
****************************************


In [227]:
X = df.iloc[:,0:2].values[2].reshape(2,1)
y = df.iloc[:,-1].values[2]

X, y

(array([[ 6],
        [10]], dtype=int64),
 6)

In [228]:
update_parameters(y, y_hat, parameters, X, A1)

C:\Users\kumar\AppData\Local\Temp\ipykernel_17012\1378376096.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters["W2"][0][0] = parameters["W2"][0][0] - 0.001*(-2 * (y-y_hat) * A1[0][0])
C:\Users\kumar\AppData\Local\Temp\ipykernel_17012\1378376096.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters["W2"][1][0] = parameters["W2"][1][0] - 0.001*(-2 * (y-y_hat) * A1[1][0])
C:\Users\kumar\AppData\Local\Temp\ipykernel_17012\1378376096.py:4: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this 

In [229]:
parameters

{'W1': array([[0.12458335, 0.13344878],
        [0.12461077, 0.13349447]]),
 'b1': array([[0.00362701],
        [0.00363158]]),
 'W2': array([[0.1477752 ],
        [0.14818986]]),
 'b2': array([[0.02760173]])}

# fourth student

In [230]:
X = df.iloc[:,0:2].values[3].reshape(2,1)
y = df.iloc[:,-1].values[3]

y_hat , A1 = L_layer_forward(X, parameters)

A0:  [[ 5]
 [12]]
W1:  [[0.12458335 0.13344878]
 [0.12461077 0.13349447]]
b1:  [[0.00362701]
 [0.00363158]]
----------------------------------------
A1:  [[2.12187303]
 [2.2728091 ]]
****************************************
A1:  [[2.12187303]
 [2.2728091 ]]
W2:  [[0.1477752 ]
 [0.14818986]]
b2:  [[0.02760173]]
----------------------------------------
A2:  [[0.6779692]]
****************************************


In [231]:
X = df.iloc[:,0:2].values[3].reshape(2,1)
y = df.iloc[:,-1].values[3]

X, y

(array([[ 5],
        [12]], dtype=int64),
 7)

In [232]:
update_parameters(y, y_hat, parameters, X, A1)

C:\Users\kumar\AppData\Local\Temp\ipykernel_17012\1378376096.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters["W2"][0][0] = parameters["W2"][0][0] - 0.001*(-2 * (y-y_hat) * A1[0][0])
C:\Users\kumar\AppData\Local\Temp\ipykernel_17012\1378376096.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters["W2"][1][0] = parameters["W2"][1][0] - 0.001*(-2 * (y-y_hat) * A1[1][0])
C:\Users\kumar\AppData\Local\Temp\ipykernel_17012\1378376096.py:4: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this 

In [233]:
parameters

{'W1': array([[0.13562189, 0.15994127],
        [0.13579618, 0.16033944]]),
 'b1': array([[0.00583472],
        [0.00586866]]),
 'W2': array([[0.17460429],
        [0.1769274 ]]),
 'b2': array([[0.04024579]])}

# Same above work we run for 5 or 10 epochs(Training)

In [234]:
def L_layer_forward1(X, parameters): 
    A = X
    L = len(parameters) // 2 ## number of layers in the neural network

    for i in range(1, L+1):
        A_pre = A   # A_pre is the input
        W1 = parameters["W" + str(i)]
        b1 = parameters["b" + str(i)]

        # print("A" + str(i-1) + ": ", A_pre)
        # print("W" + str(i) + ": ", W1)
        # print("b" + str(i) + ": ", b1)
        # print("--"*20)

        A = linear_forward(A_pre, W1, b1)
        # print("A" + str(i) + ": ", A )
        # print("**"*20)
    return A, A_pre

In [235]:
# parameters initialization
parameters = initialize_parameters([2,2,1])
epochs = 10

for i in range(epochs):

    Loss = []

    for j in range(df.shape[0]):
        
        X = df.iloc[:,0:2].values[j].reshape(2,1)
        y = df.iloc[:,-1].values[j]

        y_hat , A1 = L_layer_forward1(X, parameters)
        y_hat = y_hat[0][0]
        update_parameters(y, y_hat, parameters, X, A1)
        
        Loss.append((y-y_hat)**2)
    
    print("Epoch - ", i+1, "<-->", "Loss - ", np.array(Loss).mean())

parameters

Epoch -  1 <--> Loss -  26.28249792398698
Epoch -  2 <--> Loss -  19.438253848220803
Epoch -  3 <--> Loss -  10.13987443582752
Epoch -  4 <--> Loss -  3.385561305106485
Epoch -  5 <--> Loss -  1.3198454128484571
Epoch -  6 <--> Loss -  1.1524956147582675
Epoch -  7 <--> Loss -  1.2167000755723483
Epoch -  8 <--> Loss -  1.2516160752947996
Epoch -  9 <--> Loss -  1.2639532647966925
Epoch -  10 <--> Loss -  1.2679901889198901


{'W1': array([[0.25919461, 0.43424344],
        [0.27145721, 0.46800135]]),
 'b1': array([[0.02979873],
        [0.03253749]]),
 'W2': array([[0.43446454],
        [0.51761113]]),
 'b2': array([[0.12009632]])}

In [236]:
df.shape[0]

4

In [237]:
y_hat

5.801105261986884

# Doing Everything above with PyTorch

In [238]:
import torch
from torch import nn
torch.__version__

'2.4.1+cpu'

In [239]:
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [240]:
X = df.iloc[:,0:2].values
y = df.iloc[:,-1].values

In [241]:
X

array([[ 8,  8],
       [ 7,  9],
       [ 6, 10],
       [ 5, 12]], dtype=int64)

In [242]:
# turn data into tensors
X = torch.from_numpy(X).type(torch.float)
y = torch.from_numpy(y).type(torch.float)

In [243]:
X

tensor([[ 8.,  8.],
        [ 7.,  9.],
        [ 6., 10.],
        [ 5., 12.]])

In [244]:
y

tensor([4., 5., 6., 7.])

In [245]:
X.shape, y.shape

(torch.Size([4, 2]), torch.Size([4]))

In [246]:
# setting up the device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [247]:
# Now lets construct a model class

class student(nn.Module):
  def __init__(self):
    super().__init__()
    self.layer_1 = nn.Linear(in_features=2, out_features=2) # input layer
    self.layer_2 = nn.Linear(in_features=2, out_features=1) # hidden layer

  def forward(self, x):
    return self.layer_2(self.layer_1(x))

In [248]:
# lets replicate the above model using nn.Sequenctial()
model = nn.Sequential(
    nn.Linear(in_features=2, out_features=2),
    nn.Linear(in_features=2, out_features=1)
).to(device)

In [249]:
model

Sequential(
  (0): Linear(in_features=2, out_features=2, bias=True)
  (1): Linear(in_features=2, out_features=1, bias=True)
)

In [250]:
model.state_dict()

OrderedDict([('0.weight',
              tensor([[ 0.2192, -0.3823],
                      [-0.6509,  0.1442]])),
             ('0.bias', tensor([ 0.5387, -0.3930])),
             ('1.weight', tensor([[-0.5490,  0.2333]])),
             ('1.bias', tensor([0.3100]))])

In [251]:
# total_trainable_parameters = [2x2,+ 2 bias], [2x1,+ 1 bias] => 4+2+2+1 => 9
total_params = sum(
	param.numel() for param in model.parameters()
)
total_params

9

In [252]:
new_weights = [np.array([[0.1, 0.1], 
                        [0.1, 0.1]], dtype=np.float32),
              np.array([0., 0.], dtype=np.float32),
              np.array([[0.1],
                       [0.1]], dtype=np.float32),
              np.array([0.], dtype=np.float32)]

In [253]:
new_weights

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [254]:
# Given weights and biases
weights = [
    torch.tensor([[0.1, 0.1], [0.1, 0.1]], dtype=torch.float32),  # fc1 weight
    torch.tensor([0., 0.], dtype=torch.float32),                 # fc1 bias
    torch.tensor([[0.1], [0.1]], dtype=torch.float32),           # fc2 weight
    torch.tensor([0.], dtype=torch.float32)                      # fc2 bias
]

In [255]:
weights

[tensor([[0.1000, 0.1000],
         [0.1000, 0.1000]]),
 tensor([0., 0.]),
 tensor([[0.1000],
         [0.1000]]),
 tensor([0.])]

In [256]:
weights[2]

tensor([[0.1000],
        [0.1000]])

In [257]:
model[1]

Linear(in_features=2, out_features=1, bias=True)

In [258]:
# Assign the weights to the Sequential layers
with torch.no_grad():
    model[0].weight.copy_(weights[0])  # First Linear Layer (fc1) weights
    model[0].bias.copy_(weights[1])    # First Linear Layer (fc1) bias
    model[1].weight.copy_(weights[2].T)  # Second Linear Layer (fc2) weights
    model[1].bias.copy_(weights[3])    # Second Linear Layer (fc2) bias

# Verify the assigned weights
print("Layer 1 weights:", model[0].weight)
print("Layer 1 bias:", model[0].bias)
print("Layer 2 weights:", model[1].weight)
print("Layer 2 bias:", model[1].bias)

Layer 1 weights: Parameter containing:
tensor([[0.1000, 0.1000],
        [0.1000, 0.1000]], requires_grad=True)
Layer 1 bias: Parameter containing:
tensor([0., 0.], requires_grad=True)
Layer 2 weights: Parameter containing:
tensor([[0.1000, 0.1000]], requires_grad=True)
Layer 2 bias: Parameter containing:
tensor([0.], requires_grad=True)


In [259]:
model.state_dict()

OrderedDict([('0.weight',
              tensor([[0.1000, 0.1000],
                      [0.1000, 0.1000]])),
             ('0.bias', tensor([0., 0.])),
             ('1.weight', tensor([[0.1000, 0.1000]])),
             ('1.bias', tensor([0.]))])

In [260]:
model.parameters

<bound method Module.parameters of Sequential(
  (0): Linear(in_features=2, out_features=2, bias=True)
  (1): Linear(in_features=2, out_features=1, bias=True)
)>

In [261]:
# loss_fc and optimizer
loss_fc = nn.MSELoss() 

optimizer = torch.optim.Adam(params = model.parameters(),
                            lr = 0.001)

In [262]:
X

tensor([[ 8.,  8.],
        [ 7.,  9.],
        [ 6., 10.],
        [ 5., 12.]])

In [263]:
y

tensor([4., 5., 6., 7.])

In [264]:
# building a training and evaluation loop

epochs = 110

for epoch in range(epochs):

  model.train()

  # forward pass
  y_logits = model(X).squeeze()
  y_pred = torch.round(torch.sigmoid(y_logits))

  # calculate the loss/accuarcy
  loss = loss_fc(y_logits, y)

  # optimizer zero grad
  optimizer.zero_grad()

  # backpropagation
  loss.backward()

  # optimizer step (perform gradient descent)
  optimizer.step()

  # testing
  model.eval()
  with torch.inference_mode():

    # forward pass
    test_logits = model(X).squeeze()
    test_pred = torch.round(torch.sigmoid(test_logits))

    # calculate the loss/accuarcy
    test_loss = loss_fc(test_logits, y)


# lets print out what is happening
    if epoch % 10 == 0:
        print(f"Epoch: {epoch} | Loss: {loss:.5f}")


Epoch: 0 | Loss: 28.01570
Epoch: 10 | Loss: 27.18449
Epoch: 20 | Loss: 26.28617
Epoch: 30 | Loss: 25.31570
Epoch: 40 | Loss: 24.27124
Epoch: 50 | Loss: 23.15450
Epoch: 60 | Loss: 21.97032
Epoch: 70 | Loss: 20.72627
Epoch: 80 | Loss: 19.43214
Epoch: 90 | Loss: 18.09960
Epoch: 100 | Loss: 16.74187


## Pytorch model weights after training

In [265]:
model.state_dict()

OrderedDict([('0.weight',
              tensor([[0.2196, 0.2200],
                      [0.2196, 0.2200]])),
             ('0.bias', tensor([0.1198, 0.1198])),
             ('1.weight', tensor([[0.2204, 0.2204]])),
             ('1.bias', tensor([0.1046]))])

## our model weights after training

In [266]:
parameters

{'W1': array([[0.25919461, 0.43424344],
        [0.27145721, 0.46800135]]),
 'b1': array([[0.02979873],
        [0.03253749]]),
 'W2': array([[0.43446454],
        [0.51761113]]),
 'b2': array([[0.12009632]])}